---
title: "New"
author: "ruiling Liu"
date: '2022-11-25'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# package
```{r}
library(ggplot2)
library(dplyr)
library(ggpubr)
library(ggpmisc)
library(ggrepel)
library(psych)
library(corrplot)
library(cowplot)
library(ggsci)
library(RColorBrewer)
library(agricolae)
library(smatr)
library(ggthemes)
```
# data
```{r}
setwd("D:/2022TMmountain")
TMSdata2022 <- read.csv("2022TMSdataR.csv")

# check data
dim(TMSdata2022)
head(TMSdata2022, 6)

# Normal distribution test
plot <- ggdensity(TMSdata2022$totalmass_dry, 
          main = "density plot of totalmass_dry", 
          xlab = "totalmass_dry")
plot

ggqqplot(TMSdata2022$totalmass_dry)
hist(na.omit(TMSdata2022$totalmass_dry))

str(TMSdata2022)
shapiro.test(TMSdata2022$totalmass_dry)
shapiro.test(TMSdata2022$rootshootration)
shapiro.test(TMSdata2022$above_groundmass)
shapiro.test(TMSdata2022$SLA)
shapiro.test(TMSdata2022$root.tissue.density)
shapiro.test(TMSdata2022$specific.root.area)
shapiro.test(TMSdata2022$Root.Length.Diameter.Range.1.mm)
shapiro.test(TMSdata2022$Surface.Area.Diameter.Range.1.mm2)
shapiro.test(TMSdata2022$Volume.Diameter.Range.1.mm3)


#对海拔重命名
df0 <- rename(TMSdata2022,
             elevation = "altitude",
             SRL = "specific.root.length", 
             SRA= "specific.root.area",  
             RTD= "root.tissue.density", 
             Fine_root_length = "Root.Length.Diameter.Range.1.mm", 
             Fine_root_area = "Surface.Area.Diameter.Range.1.mm2", 
             Fine_root_volume = "Volume.Diameter.Range.1.mm3",
             Total_root_length = "Total.Root.Length.mm")
str(df0)

#查看列名
colnames(df0)
df0$species
```

# elevation
```{r include=FALSE}
display.brewer.pal(4, name = "Dark2")
display.brewer.pal(8, name = "Dark2")
brewer.pal(n = 8, name = "Dark2")
brewer.pal(n = 4, name = "Dark2")

#rootshootration随海拔变化趋势
RSmd <- lm(log10(rootshootration)~elevation,data = df0)
summary(RSmd)
plot(RSmd)

RS <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(rootshootration), 
             group = species, 
             color = species)) +
  geom_point(size = 2, alpha = 1) +
  #scale_color_tron()+
  #scale_fill_tron()+
  #scale_color_brewer(palette = "Dark2") +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  # xlab("Elevation (m)")+
  xlab(NULL)+
  ylab("Root shoot ratio")+
  ylim(-1.5,0.5)+
  geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("jhh","xpc"))) +
  #stat_smooth(mapping = c(x = elevation, y = log(rootshootration)),data = df0,method = "lm")+
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size = 4) + 
  # theme_base()+
  theme_classic()+
  # theme_bw()+
  # theme_test()+
  # theme_classic2()+
  # theme_void()+
  # theme_linedraw()+
  theme(legend.position = "none",
        #legend.direction = "horizontal",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text = element_text(size = 10, colour = "black")) 
  
  #theme(legend.position = "right", panel.background = element_rect(fill = "white", colour = "grey50"))

RS

ggplot(data = df0,aes(x = elevation, 
             y = log(rootshootration))) +
  geom_smooth(method = "lm", formula = y~x, data = df0)+
  stat_poly_eq(use_label(c("adj.R2","P","eq")))

#RMR随海拔变化趋势
RMRmd <- lm(RMR~elevation,data = df0)
summary(RMRmd)
plot(RMRmd)

scaleFUN <- function(x) sprintf("%.1f", x) 

RMR <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(RMR),
             group = species, 
             color = species)) +
  geom_point(size = 2, alpha = 1) +
  ylab("Root mass ratio")+
  ylim(-1.3,0)+
  xlab(NULL)+
  # xlab("Elevation (m)")+
  #scale_color_tron()+
  #scale_fill_tron()+
  #scale_color_brewer(palette = "Dark2",name = "Species")+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30")
                     #,name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus")
                     )+
  geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("jhh","xpc"))) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) +
  #scale_y_continuous(breaks = c(-2.5,-1.5,-0.5,0.5,0.5),labels = c("-2.5","-1.5","-0.5","0.0","0.5")) +
  #scale_fill_manual(breaks = c("cmnxj","jhh","xpc","ynp"),values = c("#1663A9","#EE4431","#614099","#B49D30"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  theme_classic()+
  theme(legend.position = "none",
    #legend.position = c(0.77,0.85),
        #legend.direction = "horizontal",
        legend.text = element_text(size = 12,face = "italic"),#修改图例标签大小
        #legend.background = element_blank(),
        panel.background = element_rect(fill = "white", colour = "grey50"),
    axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text = element_text(size = 10, colour = "black"))

RMR

ggplot(data = df0,aes(x = elevation, 
             y = log(RMR))) +
  geom_smooth(method = "lm", formula = y~x, data = df0)+
  stat_poly_eq(use_label(c("adj.R2","P")))
  
#LMR随海拔变化趋势
LMRmd <- lm(LMR~elevation,data = df0)
summary(LMRmd)
plot(LMRmd)


LMR <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(LMR), 
             group = species, 
             color = species)) +
  geom_point(size = 2, alpha = 1) +
  ylab("Leaf mass ratio") +
  #xlab("Elevation (m)")+
  xlab(NULL)+
  ylim(-1,0.1) +
  # scale_color_tron()+
  # scale_fill_tron()+
  #scale_color_brewer(palette = "Dark2") +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("ynp"))) + 
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"))

LMR

ggplot(data = df0,aes(x = elevation, 
             y = log(LMR))) +
  geom_smooth(method = "lm", formula = y~x, data = df0)+
  stat_poly_eq(use_label(c("adj.R2","P")))



#SMR随海拔变化趋势
SMRmd <- lm(SMR~elevation,data = df0)
summary(SMRmd)
plot(SMRmd)


SMR <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(SMR), 
             group = species, 
             color = species)) +
  geom_point(size = 2, alpha = 1) +
  xlab(NULL)+
  # xlab("Elevation (m)")+
  # xlab(NULL)+
  ylab("Stem mass ratio")+
  ylim(-0.9,0.2)+
  # scale_color_tron()+
  # scale_fill_tron()+
  #scale_color_brewer(palette = "Dark2") +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("ynp","jhh","xpc"))) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.x = element_blank(),
        axis.text = element_text(size = 10, colour = "black"))
SMR

ggplot(data = df0,aes(x = elevation, 
             y = log(SMR))) +
  geom_smooth(method = "lm", formula = y~x, data = df0)+
  stat_poly_eq(use_label(c("adj.R2","P")))


#Fig 1
plot_grid(LMR,RMR,SMR,RS,
          labels = "AUTO", 
          label_size = 12, 
          ncol = 2
          #align = "v", 
          #label_x = c(0.1,0.6,0.1,0.6),
          #label_y = c(0.9,0.9,0.4,0.4)
          )

ggsave("Fig 1.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 28,height = 25,units = "cm")

ggsave("Fig 1.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 28,height = 25,units = "cm")

#SLA随海拔变化趋势
SLAmd <- lm(SLA~elevation,data = df0)
summary(SLAmd)
plot(SLAmd)


SLA <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(SLA),
             group = species, 
             color = species)) +
  geom_point(size = 2, alpha = 1) +
  xlab(NULL)+
  #xlab("Elevation")+
  ylim(2,3.5)+
  ylab("Specific leaf area (cm2/g)")+
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("cmnxj"))) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  #scale_y_continuous(breaks = c("5.0","6.0","7.0","8.0"),labels = c("5.0","6.0","7.0","8.0"))+
  theme_classic()+
  theme(legend.position = c(0.75,0.85),
        #axis.text.x = element_blank(),
        legend.text = element_text(size = 10,face = "italic"),
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        #axis.text.x = element_text(size = 16, colour = "black"),
        axis.text.y = element_text(size = 10, colour = "black")
        ) 
SLA

##
ggplot(data = df0,aes(x = elevation, 
             y = log(SLA))) +
  geom_smooth(method = "lm", formula = y~x, data = df0)+
  stat_poly_eq(use_label(c("adj.R2","P")))

#SRL随海拔变化趋势
SRLmd <- lm(SRL~elevation,data = df0)
summary(SRLmd)
plot(SRLmd)


SRL <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(SRL), 
             group = species, 
             color = species)) +
  geom_point(size = 2, alpha = 1) +
  xlab(NULL)+
  #xlab("Elevation")+
  ylab("Specific root length (mm/g)")+
  ylim(3,5.8)+
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("xpc"))) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  theme_classic() + 
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        #axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"))
SRL

##
ggplot(data = df0,aes(x = elevation, 
             y = log(SRL))) +
  geom_smooth(method = "lm", formula = y~x, data = df0)+
  stat_poly_eq(use_label(c("adj.R2","P")))

#RTD随海拔变化趋势
RTDmd <- lm(log(RTD)~elevation,data = df0)
summary(RTDmd)
plot(RTDmd)


RTD <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(RTD), 
             group = species, 
             color = species)) +
  geom_point(size = 2, alpha = 1) +
  ylim(-6.5,-2.9)+
  xlab(NULL)+
  #xlab("Elevation (m)")+
  ylab("Root tissue density (g/mm3)")+
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  geom_smooth(method = "lm", formula = y~x,data = subset(df0, species ==c("xpc"))) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  theme_classic() +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black")
        #,axis.text.x = element_text(size = 13, colour = "black")
        )
RTD

##
ggplot(data = df0,aes(x = elevation, 
             y = log(RTD))) +
  geom_smooth(method = "lm", formula = y~x, data = df0)+
  stat_poly_eq(use_label(c("adj.R2","P")))

#SRA随海拔变化趋势
SRAmd <- lm(log(SRA)~elevation,data = df0)
summary(SRAmd)
plot(SRAmd)


SRA <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(SRA), 
             group = species, 
             color = species)) +
  xlab(NULL)+
  #xlab("Elevation (m)")+
  ylim(3.9,6.5)+
  ylab("Specific root area (mm2/g)")+
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x,data = subset(df0, species ==c("xpc"))) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black")
        #,axis.text.x = element_text(size = 16, colour = "black")
        )
SRA

ggplot(data = df0,aes(x = elevation, 
             y = log(SRA))) +
  geom_smooth(method = "lm", formula = y~x, data = df0)+
  stat_poly_eq(use_label(c("adj.R2","P")))

#Fig 2
plot_grid(SRL,SLA,SRA,RTD,
          labels = "AUTO",
          ncol = 2,
          label_size = 12)

ggsave("Fig 2.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 28,height = 25,units = "cm")

ggsave("Fig 2.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 28,height = 25,units = "cm")

plot_grid(SLA,SRL,SRA,RTD,LMR,SMR,RMR,RS,
          labels = "AUTO",
          ncol = 3,
          align = "v",
          label_size = 14)+
  theme(plot.margin = margin(0.1,0.1,1.0,0.1,unit = "cm"))

ggsave("Fig 1_20240109_1.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 25,height = 22,units = "cm")


#Fine_root_length随海拔变化趋势
Fine_root_lengthmd <- lm(log(Fine_root_length)~elevation,data = df0)
summary(Fine_root_lengthmd)
plot(Fine_root_lengthmd)


Fine_root_length <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(Fine_root_length), 
             group = species, 
             color = species)) +
  #xlab("Elevation (m)")+
  xlab(NULL)+
  ylab("Fine root Length (mm)")+
  ylim(2.75,4.7)+
  #scale_color_tron()+
  #scale_fill_tron()+
  geom_point(size = 2, alpha = 1) +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  geom_smooth(method = "lm", formula = y~x,data = subset(df0, species ==c("xpc"))) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        #axis.text.x = element_text(size = 14, colour = "black"),
        axis.text.y = element_text(size = 10, colour = "black"))
Fine_root_length


#Fine_root_area随海拔变化趋势
Fine_root_areamd <- lm(log(Fine_root_area)~elevation,data = df0)
summary(Fine_root_areamd)
plot(Fine_root_areamd)


Fine_root_area <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(Fine_root_area), 
             group = species, 
             color = species)) +
  #xlab("Elevation (m)")+
  xlab(NULL)+
  ylab("Fine root area (mm2)")+
  ylim(3,5.05)+
  #scale_color_tron()+
  #scale_fill_tron()+
  geom_point(size = 2, alpha = 1) +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  geom_smooth(method = "lm", formula = y~x,data = subset(df0, species ==c("xpc"))) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")), size=4) + 
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        #axis.text.x = element_text(size = 13, colour = "black"),
        axis.text.y = element_text(size = 10, colour = "black"))
Fine_root_area


#Fine_root_volume随海拔变化趋势
Fine_root_volumemd <- lm(log(Fine_root_volume)~elevation,data = df0)
summary(Fine_root_volumemd)
plot(Fine_root_volumemd)


Fine_root_volume <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(Fine_root_volume), 
             group = species, 
             color = species)) +
  #xlab("Elevation (m)")+
  xlab(NULL)+
  ylab("Fine root volume (mm3)")+
  ylim(2.3,4.5)+
  #scale_color_tron()+
  #scale_fill_tron()+
  geom_point(size = 2, alpha = 1) +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  geom_smooth(method = "lm", formula = y~x,data = subset(df0, species ==c("xpc"))) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  theme_classic()+
  theme(legend.position = c(0.74,0.845),
        panel.background = element_rect(fill = "white", colour = "grey50"),axis.text.x = element_blank(),
        legend.text = element_text(size = 7,face = "italic"),
        axis.title = element_text(size = 12, color = "black"),
        #axis.text.x = element_text(size = 13, colour = "black"),
        axis.text.y = element_text(size = 10, colour = "black"))
Fine_root_volume


#Fig 11
plot_grid(Fine_root_length,Fine_root_area,Fine_root_volume,
          labels = "AUTO",
          ncol = 3,
          label_size = 12)

ggsave("Fig 11.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 40,height = 15,units = "cm")

ggsave("Fig 11.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 40,height = 13,units = "cm")


#root_dry随海拔变化趋势
RMmd <- lm(log(root_dry)~elevation,data = df0)
summary(RMmd)
plot(RMmd)

RM <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(root_dry), 
             group = species, 
             color = species)) +
  geom_point(size = 2, alpha = 1) +
  #scale_color_tron()+
  #scale_fill_tron()+
  #scale_color_brewer(palette = "Dark2") +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  xlab(NULL)+
  # xlab("Elevation (m)")+
  ylab("Root dry mass (g)")+
  ylim(-1.6,1.25)+
  #geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("jhh","xpc"))) +
  #stat_smooth(mapping = c(x = elevation, y = log(rootshootration)),data = df0,method = "lm")+
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size = 4) + 
  theme_classic()+
  theme(legend.position = "none",
        #legend.direction = "horizontal",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text = element_text(size = 10, colour = "black")) 
  
  #theme(legend.position = "right", panel.background = element_rect(fill = "white", colour = "grey50"))

RM

ggplot(data = df0,aes(x = elevation, 
             y = log(stem_dry),group = species, 
             color = species)) +
  geom_smooth(method = "lm", formula = y~x, data = df0)+
  stat_poly_eq(use_label(c("adj.R2","P","eq")))


#totalmass_dry
TMmd <- lm(log(totalmass_dry)~elevation,data = df0)
summary(TMmd)
plot(TMmd)

TM <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log(totalmass_dry), 
             group = species, 
             color = species)) +
  geom_point(size = 3, alpha = 1) +
  #scale_color_tron()+
  #scale_fill_tron()+
  #scale_color_brewer(palette = "Dark2") +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  xlab("Elevation (m)")+
  ylab("Total dry mass (g)")+
  ylim(-2,3.7)+
  #geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("jhh","xpc"))) +
  #stat_smooth(mapping = c(x = elevation, y = log(rootshootration)),data = df0,method = "lm")+
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size = 5) + 
  theme(legend.position = "none",
        #legend.direction = "horizontal",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        #axis.text.x = element_blank(),
        axis.title = element_text(size = 22, color = "black"),
        axis.text = element_text(size = 14, colour = "black")) 
  
  #theme(legend.position = "right", panel.background = element_rect(fill = "white", colour = "grey50"))

TM


#leaf_totalmass
LMmd <- lm(log(leaf_totalmass)~elevation,data = df0)
summary(LMmd)
plot(LMmd)

LM <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(leaf_totalmass), 
             group = species, 
             color = species)) +
  geom_point(size = 2, alpha = 1) +
  #scale_color_tron()+
  #scale_fill_tron()+
  #scale_color_brewer(palette = "Dark2") +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  # xlab("Elevation (m)")+
  xlab(NULL)+
  ylab("Leaf dry mass (g)")+
  ylim(-1.2,1.35)+
  #geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("jhh","xpc"))) +
  #stat_smooth(mapping = c(x = elevation, y = log(rootshootration)),data = df0,method = "lm")+
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size = 4) + 
  theme_classic()+
  theme(legend.position = "none",
        #legend.direction = "horizontal",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text = element_text(size = 10, colour = "black")) 
  
  #theme(legend.position = "right", panel.background = element_rect(fill = "white", colour = "grey50"))

LM



#stem_dry
SMmd <- lm(log(stem_dry)~elevation,data = df0)
summary(SMmd)
plot(SMmd)

SM <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log10(stem_dry), 
             group = species, 
             color = species)) +
  geom_point(size = 2, alpha = 1) +
  #scale_color_tron()+
  #scale_fill_tron()+
  #scale_color_brewer(palette = "Dark2") +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  # xlab("Elevation (m)")+
  xlab(NULL)+
  ylab("Stem dry mass (g)")+
  ylim(-1.3,1.35)+
  #geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("jhh","xpc"))) +
  #stat_smooth(mapping = c(x = elevation, y = log(rootshootration)),data = df0,method = "lm")+
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size = 4) + 
  theme_classic()+
  theme(legend.position = "none",
        #legend.direction = "horizontal",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text = element_text(size = 10, colour = "black")) 
  
  #theme(legend.position = "right", panel.background = element_rect(fill = "white", colour = "grey50"))

SM

#Fig S1
plot_grid(Fine_root_length,Fine_root_area,Fine_root_volume,
          LM,SM,RM,
          align = "v",
          labels = "AUTO", 
          label_size = 14, 
          ncol = 3)+
  theme(plot.margin = margin(0.1,0.1,1.0,0.1, unit = "cm"))

ggsave("Fig S120240109_1.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 28,height = 16,units = "cm")

# ggsave("Fig S1.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 45,height = 30,units = "cm")
```

# relationship
```{r echo=FALSE}
#install.packages("smatr")
df2 <- df0 %>%
  select(
    species,
    elevation,
    totalmass_dry,
    rootshootration,
    above_groundmass,
    root_dry,
    RMR,
    leaf_totalmass,
    LMR,
    stem_dry,
    SMR,
    SLA,
    SRL,
    RTD,
    SRA,
    Fine_root_length,
    Fine_root_area,
    Fine_root_volume
  )

str(df2)

df_col <- c(
    "totalmass_dry",
    "rootshootration",
    "above_groundmass",
    "root_dry",
    "RMR",
    "leaf_totalmass",
    "LMR",
    "stem_dry",
    "SMR",
    "SLA",
    "SRL",
    "RTD",
    "SRA",
    "Fine_root_length",
    "Fine_root_area",
    "Fine_root_volume")

library(smatr)
str(df2)
lm <- lm(SLA~SRL,data = df2)
anova(lm)
summary(lm)

fit <- sma(SLA~SRL,data = df2, log = "xy")
summary(fit)
xax <- defineAxis(major.ticks = c(200,300,400,500,600))
yax <- defineAxis(major.ticks = c(100,200,300,400,500))
plot(fit, xaxis=xax,yaxis=yax)


####-----#####MASS 
#####RMR vs LMR
str(df0)
stem_dry
leaf_totalmass
root_dry
df0 %>% 
  ggplot(aes(x = log(leaf_totalmass), 
             y = log(root_dry), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"))

colnames(df3)
summary(df3)

colnames(df2)

fit24 <- sma(root_dry~leaf_totalmass*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit24)
plot(fit24)

data24 <- data.frame(fit24[["data"]])
pval24 <- fit24[["pval"]] 


p24 <- ggplot(df2,
              mapping = aes(x=log10(leaf_totalmass),
                                y=log10(root_dry),
                                colour=species)) +
  xlab("Leaf dry mass (g)") +
  ylab("Root dry mass (g)") + 
  xlim(-1.588, 0.9) +
  ylim(-1.588, 0.9) +
  #scale_color_tron()+
  #scale_fill_tron()+
  geom_point(size = 2)+
  # geom_point(aes(size = elevation), alpha = 0.5) +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),
                     name = "Species",
                     breaks = c("cmnxj","jhh","xpc","ynp"),
                     labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  # scale_x_continuous(expand = c(0, 0), limits = c(0, 3.5))+
  # scale_y_continuous(expand = c(0, 0), limits = c(0, 3.5)) +
  #geom_point(aes(shape = species))+
  #stat_poly_line(formula = y ~ x,method = "lm") +
  stat_poly_line(method = "lm",formula = y ~ x) +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  annotate("text", label = c("Slope\njhh-ynp:**\nxpc-ynp:**"), x = -0.8, y = -0.3, size = 4)+
  #geom_abline(intercept = 0, slope = 1)+
  #abline(0, 0.5, col = "black")+
  geom_abline(intercept = 0, slope = 1, size=1.3, linetype=2)+
  # coord_equal()+
  theme_classic()+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", 
                                        colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        legend.text = element_text(size = 10,face = "italic"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))

p24


####RMR vs SMR
stem_dry
leaf_totalmass
root_dry
df0 %>% 
  ggplot(aes(x = log(stem_dry), 
             y = log(root_dry), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "top",panel.background = element_rect(fill = "white", colour = "grey50"))

fit25 <- sma(root_dry~stem_dry*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit25)
plot(fit25)

data25 <- data.frame(fit25[["data"]])
pval25 <- fit25[["pval"]] 

p25 <- ggplot(df2,
              mapping = aes(x=log10(stem_dry),
                            y=log10(root_dry), 
                            colour=species)) +
  xlab("Stem dry mass (g)") +
  ylab("Root dry mass (g)") + 
  xlim(-1.555, 0.715) +
  ylim(-1.555, 0.715)+
  #xlim(2.15,3.05) +
  #ylim(-1.3,0.15) +
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),
                     name = "Species",
                     breaks = c("cmnxj","jhh","xpc","ynp"),
                     labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  # geom_point(size = 3, alpha = 1) +
  geom_point(size = 2)+
  # geom_point(aes(size = elevation), alpha = 0.5) +
  #geom_point(aes(shape = species))+
  stat_poly_line(method = "lm",formula = y ~ x) +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  annotate("text", label = c("Slope\nxpc-ynp:**"), x = -1, y = -0.3, size = 4)+
  geom_abline(intercept = 0, slope = 1, size=1.3, linetype=2)+
  # coord_equal()+
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        legend.text = element_text(size = 10,face = "italic"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))
p25


####LMR vs SMR
stem_dry
leaf_totalmass
root_dry
df0 %>% 
  ggplot(aes(x = log(stem_dry), 
             y = log(leaf_totalmass), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"))

fit26 <- sma(leaf_totalmass~stem_dry*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit26)
plot(fit26)

data26 <- data.frame(fit26[["data"]])
pval26 <- fit26[["pval"]] 

p26 <- ggplot(df2,
              mapping = aes(x=log10(stem_dry),
                            y=log10(leaf_totalmass),
                            colour=species)) +
  xlab("Stem dry mass (g)") +
  ylab("Leaf dry mass (g)") + 
  xlim(-1.35,0.815) +
  ylim(-1.35,0.815) +
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),
                     name = "Species",
                     breaks = c("cmnxj","jhh","xpc","ynp"),
                     labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  # geom_point(aes(size = elevation), alpha = 0.5) +
  geom_point(size = 2)+
  # geom_point(size = 3, alpha = 1) +
  #geom_point(aes(shape = species))+
  stat_poly_line(formula = y ~ x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  annotate("text", label = c("Slope:ns"), x = -1, y = 0, size = 4)+
  #annotate(geom = "segment",x=-1,y=-1.5,xend=0.5,yend = 0.5)+
  geom_abline(intercept = 0, slope = 1, size=1.3, linetype=2)+
  # coord_equal()+
  theme_classic()+
  theme(legend.position ="none",
    #legend.position = c(0.7,0.15),
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        legend.text = element_text(size = 10,face = "italic"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))
p26


######traits
#####SLA vs SRL
P1 <- df0 %>% 
  ggplot(aes(x = log(SLA), 
             y = log(SRL), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"))
P1

fit1 <- sma(SRL~SLA*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit1)
plot(fit1)

data1 <- fit1[["data"]]
pval <- fit1[["pval"]] 

p1 <- ggplot(df2,
             mapping = aes(x=log10(SLA),
                           y=log10(SRL), 
                           group = species, 
                           color = species)) +
  xlab("Specific leaf area (cm2/g)") +
  #xlab(NULL)+
  ylab("Specific root length (mm/g)") + 
  ylim(2.9,5.8)+
  # xlim(2,5)+
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  # geom_point(size = 3, alpha = 1) +
  # geom_point(aes(size = elevation), alpha = 0.5) +
  geom_point(size = 2)+
  geom_smooth(method = "lm", formula = y~x,data = subset(df2, species == c("xpc"))) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  # geom_point(aes(size = elevation), alpha = 0.5) +
# geom_abline(intercept = 0, slope = 1, size=1.3, linetype=2)+
#   coord_equal()+
  # theme_classic()+
  theme_classic()+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        #,axis.text.x = element_blank()
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black")
        )

p1                 
                  
#####SLA vs SRA
P2 <- df0 %>% 
  ggplot(aes(x = log(SLA), 
             y = log(SRA), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"))
P2

fit2 <- sma(SRA~SLA*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit2)
plot(fit2)



data2 <- data.frame(fit2[["data"]])
pval2 <- fit2[["pval"]] 

p2 <- ggplot(df2,mapping = aes(x=log10(SLA),
                               y=log10(SRA),
                               group = species, 
                               colour=species)) +
  xlab("Specfic leaf area (cm2/g)") +
  #xlab(NULL)+
  ylab("Specific root area (mm2/g)") + 
  #scale_color_tron()+
  #scale_fill_tron()+
  # xlim(2.15,3.05) +
  ylim(3.8,6.5) +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  # geom_point(size = 3, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x,data = subset(df2, species ==c("jhh"))) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  # geom_point(aes(size = elevation), alpha = 0.5) +
  geom_point(size = 2)+
# geom_abline(intercept = 0, slope = 1, size=1.3, linetype=2)+
  # coord_equal()+
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),#,axis.text.x = element_blank()
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black")
        )                 
p2

 
#####SLA vs RTD
P3 <- df0 %>% 
  ggplot(aes(x = log(SLA), 
             y = log(RTD), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"))
P3

fit3 <- sma(RTD~SLA*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit3)
plot(fit3)

data3 <- data.frame(fit3[["data"]])
pval3 <- fit3[["pval"]] 

p3 <- ggplot(df2,
             mapping = aes(x=log10(SLA),
                           y=log10(RTD),
                           group = species,
                           colour=species)) +
  xlab("Specific leaf area (cm2/g)") +
  ylab("Root tissue density (g/mm3)") + 
  #xlim(2.15,3.05) +
  ylim(-6.5,-2.5) +
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  #scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  # geom_point(size = 3, alpha = 1) +
  # geom_point(aes(size = elevation), alpha = 0.5) +
  geom_point(size = 2)+
  geom_smooth(method = "lm", formula = y~x,data = subset(df2, species ==c("jhh"))) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  theme_classic()+
  theme(#legend.position = c(0.75,0.85),
        legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12,color = "black"),
        legend.text = element_text(size = 10,face = "italic"),
        axis.text.y = element_text(size = 10,colour = "black"),
        axis.text.x = element_text(size = 10,colour = "black"))
p3

#Fig 3
plot_grid(p1,p2,p3,
          labels = "AUTO", 
          ncol = 3,
          label_size = 12)

ggsave("Fig 3.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 40,height = 13,units = "cm")

ggsave("Fig 3.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 40,height = 13,units = "cm")
#####SRA vs SRL
P4 <- df0 %>% 
  ggplot(aes(x = log(SRA), 
             y = log(SRL), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"))
P4

fit4 <- sma(SRL~SRA*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit4)
plot(fit4)

data4 <- data.frame(fit4[["data"]])
pval4 <- fit4[["pval"]] 

p4 <- ggplot(df2,
             mapping = aes(x=log10(SRA),
                           y=log10(SRL),
                           group = species,
                           colour=species)) +
  xlab("Specific root area (mm2/g)") +
  ylab("Specific root length (mm/g)") + 
  #xlim(2.15,3.05) +
  ylim(2.9,5.5) +
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  # geom_point(size = 3, alpha = 1) +
  # geom_point(aes(size = elevation), alpha = 0.5)+
  geom_point(size = 2)+
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  annotate("text", label = "Slope:ns", x = 5.5, y = 3.5, size = 4)+
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        #legend.text = element_text(size = 12,face = "italic"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))
p4

####SRL vs RTD
P5 <- df0 %>% 
  ggplot(aes(x = log(RTD), 
             y = log(SRL), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"))
P5

fit5 <- sma(SRL~RTD*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit5)
plot(fit5)

data5 <- data.frame(fit5[["data"]])
pval5 <- fit5[["pval"]] 

p5 <- ggplot(df2,
             mapping = aes(
               x=log10(RTD),
               y=log10(SRL), 
               colour=species)) +
  xlab("Root tissue density (g/mm3)") +
  ylab("Specific root length (mm/g)") + 
  #xlim(2.15,3.05) +
  ylim(3.0,5.9) +
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  # geom_point(size = 3, alpha = 1) +
  # geom_point(aes(size = elevation), alpha = 0.5) +
  geom_point(size = 2)+
  #stat_poly_line(formula = y ~ x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        #legend.text = element_text(size = 12,face = "italic"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))
p5

####SRA vs RTD
P6 <- df0 %>% 
  ggplot(aes(x = log(RTD), 
             y = log(SRA), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"))
P6

fit6 <- sma(SRA~RTD*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit6)
plot(fit6)

data6 <- data.frame(fit6[["data"]])
pval6 <- fit6[["pval"]] 

p6 <- ggplot(df2,
             mapping = aes(
               x=log10(RTD),
               y=log10(SRA), 
               colour=species)) +
  xlab("Root tissue density (g/mm3)") +
  ylab("Specific root area (mm2/g)") + 
  #xlim(2.15,3.05) +
  ylim(3.8,6.8) +
  #scale_color_tron()+
  #scale_fill_tron()+
  #scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  # geom_point(size = 3, alpha = 1) +
  # geom_point(aes(size = elevation), alpha = 0.5) +
  geom_point(size = 2)+
  stat_poly_line(formula = y ~ x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  annotate("text", label = "Slope:ns", x = -6, y = 4.5, size = 4)+
  theme_classic()+
  theme(#legend.position = "none",
        legend.position = c(0.73,0.845),
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        legend.text = element_text(size = 10,face = "italic"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))
p6


#Fig 4
plot_grid(p4,p5,p6,
          labels = "AUTO", 
          ncol = 3,
          label_size = 12)

ggsave("Fig 4.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 40,height = 13,units = "cm")

ggsave("Fig 4.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 40,height = 13,units = "cm")

#Fig 3
plot_grid(
          p1,p2,p3,
          p4,p5,p6,
          p24,p25,p26,
          labels = "AUTO", 
          align = "v",
          ncol = 3,
          label_size = 14)+
  theme(plot.margin = margin(0.1,0.1,0.1,0.1,unit = "cm"))

ggsave("Fig 3_20240120_1.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 25,height = 25,units = "cm")

ggsave("Fig 3.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 45,height = 45,units = "cm")


####-----#####MASS ratio
#####RMR vs LMR
df0 %>% 
  ggplot(aes(x = log(LMR), 
             y = log(RMR), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"))


fit21 <- sma(RMR~LMR*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit21)
plot(fit21)

data21 <- data.frame(fit21[["data"]])
pval21 <- fit21[["pval"]] 

p21 <- ggplot(df2,
              mapping = aes(x=log10(LMR),
                            y=log10(RMR), 
                            colour=species)) +
  xlab("Leaf mass ratio") +
  ylab("Root mass ratio") + 
  #xlim(2.15,3.05) +
  ylim(-1.3,-0.02) +
  xlim(-1.3,-0.02) + 
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  # geom_point(size = 3, alpha = 1) +
  # geom_point(aes(size = elevation), alpha = 0.5)+
  geom_point(size = 2)+
  geom_abline(intercept = 0, slope = 1, size=1.3, linetype=2)+
  # coord_equal()+
  #geom_point(aes(shape = species))+
  #stat_poly_line(formula = y ~ x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        legend.text = element_text(size = 10,face = "italic"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))
p21


####RMR vs SMR
df0 %>% 
  ggplot(aes(x = log(SMR), 
             y = log(RMR), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "top",panel.background = element_rect(fill = "white", colour = "grey50"))

fit22 <- sma(RMR~SMR*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit22)
plot(fit22)

data22 <- data.frame(fit22[["data"]])
pval22 <- fit22[["pval"]] 

p22 <- ggplot(df2,
              mapping = aes(x=log10(SMR),
                            y=log10(RMR), 
                            colour=species)) +
  xlab("Stem mass ratio") +
  ylab("Root mass ratio") + 
  #xlim(2.15,3.05) +
  ylim(-1.3,0.15) +
  xlim(-1.3,0.15) + 
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),
                     name = "Species",
                     breaks = c("cmnxj","jhh","xpc","ynp"),
                     labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  # geom_point(size = 3, alpha = 1) +
  # geom_point(aes(size = elevation), alpha = 0.5)+
  geom_point(size = 2)+
  geom_abline(intercept = 0, slope = 1, size=1.3, linetype=2)+
  # coord_equal()+
  #geom_point(aes(shape = species))+
  stat_poly_line(method = "lm",formula = y ~ x,data = subset(df2, species ==c("cmnxj","jhh","ynp"))) +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  annotate("text", label = c("Slope\n cmnxj-ynp:**\njhh-ynp:***\nxpc-ynp:**"), x = -0.3, y = 0, size = 4)+
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        legend.text = element_text(size = 10,face = "italic"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))
p22


####LMR vs SMR
df0 %>% 
  ggplot(aes(x = log(SMR), 
             y = log(LMR), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"))

fit23 <- sma(LMR~SMR*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit23)
plot(fit23)

data23 <- data.frame(fit23[["data"]])
pval23 <- fit23[["pval"]] 

p23 <- ggplot(df2,
              mapping = aes(x=log10(SMR),
                            y=log10(LMR), 
                            colour=species)) +
  xlab("Stem mass ratio") +
  ylab("Leaf mass ratio") + 
  xlim(-1,0.3) +
  ylim(-1,0.3) +
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  # geom_point(size = 3, alpha = 1) +
  # geom_point(aes(size = elevation), alpha = 0.5)+
  geom_point(size = 2)+
  geom_abline(intercept = 0, slope = 1, size=1.3, linetype=2)+
  # coord_equal()+
  # scale_size("elevation", range = c(1,3))+
  #geom_point(aes(shape = species))+
  stat_poly_line(formula = y ~ x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  annotate("text", label = c("Slope\n cmnxj-jhh:***\ncmnxj-ynp:*\njhh-xpc:*\njhh-ynp:***\nxpc-ynp:**"), x = -0.7, y = -0.7, size = 4)+
  theme_classic()+
  theme(legend.position = c(0.735,0.81),panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        legend.text = element_text(size = 10,face = "italic"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))
p23

#Fig 5
plot_grid(p21,p22,p23,
          p1,p2,p3,
          p4,p5,p6,
          labels = "AUTO", 
          ncol = 3,
          label_size = 12)

ggsave("Fig 5.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 45,height = 45,units = "cm")

ggsave("Fig 5.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 40,height = 13,units = "cm")

####-----#####ROOT TRAITS
#####Fine_root_area vs Fine_root_length
fit31 <- sma(Fine_root_area~Fine_root_length*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit31)
plot(fit31)

data31 <- data.frame(fit31[["data"]])
pval31 <- fit31[["pval"]] 

p31 <- ggplot(df2,
              mapping = aes(x=log10(Fine_root_length),
                            y=log10(Fine_root_area), 
                            colour=species)) +
  xlab("Fine root length (mm)") +
  ylab("Fine root area (mm2)") + 
  #xlim(2.15,3.05) +
  ylim(2.9,4.55) +
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  geom_point(size = 2)+
  # geom_point(aes(size = elevation), alpha = 0.5)+
  # geom_point(size = 3, alpha = 1) +
  #geom_point(aes(shape = species))+
  stat_poly_line(formula = y ~ x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  annotate("text", label = "Slope:ns", x = 4, y = 3.5, size = 4)+
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        legend.text = element_text(size = 10,face = "italic"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))
p31

####Fine_root_length vs Fine_root_volume
fit32 <- sma(Fine_root_volume~Fine_root_length*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit32)
plot(fit32)

data32 <- data.frame(fit32[["data"]])
pval32 <- fit32[["pval"]] 

p32 <- ggplot(df2,
              mapping = aes(x=log10(Fine_root_length),
                            y=log10(Fine_root_volume), 
                            colour=species)) +
  xlab("Fine root length (mm)") +
  ylab("Fine root volume (mm3)") + 
  #xlim(2.15,3.05) +
  ylim(2.3,4.0) +
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),
                     name = "Species",
                     breaks = c("cmnxj","jhh","xpc","ynp"),
                     labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  # geom_point(aes(size = elevation), alpha = 0.5)+
  geom_point(size = 2)+
  # geom_point(size = 3, alpha = 1) +
  #geom_point(aes(shape = species))+
  stat_poly_line(formula = y ~ x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  annotate("text", label = "Slope:ns", x = 4, y = 2.9, size = 4)+
  theme_classic()+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        legend.text = element_text(size = 10,face = "italic"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))
p32

####Fine_root_volume vs Fine_root_area
fit33 <- sma(Fine_root_area~Fine_root_volume*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit33)
plot(fit33)

data33 <- data.frame(fit33[["data"]])
pval33 <- fit33[["pval"]] 

p33 <- ggplot(df2,
              mapping = aes(x=log10(Fine_root_volume),
                            y=log10(Fine_root_area), 
                            colour=species)) +
  xlab("Fine root volume (mm3)") +
  ylab("Fine root area (mm2)") + 
  #xlim(2.15,3.05) +
  ylim(2.9,4.55) +
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),
                     name = "Species",
                     breaks = c("cmnxj","jhh","xpc","ynp"),
                     labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  # geom_point(size = 2, alpha = 1) +
  # geom_point(aes(size = elevation), alpha = 0.5)+
  geom_point(size = 2)+
  #geom_point(aes(shape = species))+
  stat_poly_line(formula = y ~ x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size=4) + 
  annotate("text", label = "Slope:ns", x = 3.65, y = 3.5, size = 4)+
  theme_classic()+
  theme(#legend.position = c(0.73,0.835),
        legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        legend.text = element_text(size = 10,face = "italic"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))
p33


#Fig 6
plot_grid(p31,p32,p33,
          labels = "AUTO", 
          ncol = 3,
          label_size = 12)

ggsave("Fig 6.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 40,height = 15,units = "cm")

ggsave("Fig 6.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 40,height = 13,units = "cm")

#Fig S2
plot_grid(
          p31,p32,p33,p21,p22,p23,
          align = "v",
          labels = "AUTO", 
          ncol = 3,
          label_size = 14)+
  theme(plot.margin = margin(0.1,0.1,0.1,0.1,unit = "cm"))

ggsave("Fig S320240120_1.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 28,height = 16,units = "cm")

ggsave("Fig S2.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 42,height = 22,units = "cm")

```

# PCA
```{r}
############################
###3.3 PCA

library(vegan)
library(psych)
library(dplyr)
library(tidyverse)
library(factoextra)
library(viridis)

str(df2)

df4 <- df2 %>% 
  select(species,elevation,rootshootration,RMR,LMR,SMR,SLA,SRL,RTD,SRA,Fine_root_length,Fine_root_area,Fine_root_volume) 
str(df4)

df5 <- log(df4[,-c(1:2)])

# make pca
spe.pca <- FactoMineR::PCA(df5)
spe.pca$ind$coord
spe.pca$var$coord
spe.pca$var$cor

# part1(main)
fviz_pca_biplot(spe.pca,
                axes = c(1,2),
                col.ind = df2$species,
                palette = c("#1663A9","#EE4431","#614099","#B49D30"),
                pointsize = df2$elevation,
                #palette = "npg",
                addEllipses = TRUE,
                ellipse.level = 0.95,
                label = "var",
                col.var = "black",
                repel = 0.3,
                geom.ind = "point",
                geom.var = c("arrow","text"),
                legend.title = c(color = "Species"),
                xlab = "PCA 1 (35.9%)",
                ylab = "PCA 2 (29.4%)",
                title = "PCA")+
  scale_shape_manual(values = c(15,16,17,18))+
  theme_classic()+
  #scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))
theme(#legend.position = c(0.75,0.85),
  panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        legend.text = element_text(size = 10),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))+
  scale_size(range = c(1, 10), 
                    breaks = seq(100, 1500, 300))+
  guides(size = guide_legend(title = "Elevation",
  override.aes = list(shape = 21)
  ))

# ,name = "Species",breaks = c("cmnxj","jhh","xpc","ynp")  
# ,labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus")

ggsave("Fig 7_0.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 25,height = 20,units = "cm")

ggsave("Fig 7_20240109.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 25,height = 20,units = "cm")


# part2
spe.pca$var$coord
spe.pca$var$cor
spe.pca$var

trait <- c("rootshootration","RMR","LMR","SMR","SLA","SRL",
           "RTD","SRA","Fine_root_length","Fine_root_area",
           "Fine_root_volume")
data_var <- spe.pca$var$coord[,1:2]
data_var <- as.data.frame(data_var) 
write.csv(data_var,"data var.csv")

#保存并修改了trait的名称
# data_var <- rename(data_var,
#              RSR = "rootshootration",
#              FRL = "Fine_root_length", 
#              FRA= "Fine_root_area",  
#              FRV= "Fine_root_volume")
data_var <- read.csv("data var.csv",header = TRUE)
str(data_var)

part1 <- ggplot(data = data_var,
                aes(x = Dim.1, y = reorder(Trait,Dim.1)))+
  geom_bar(stat = "identity",aes(fill = Dim.1))+
  xlab("PCA 1")+
  ylab(NULL)+
  scale_color_viridis(option = "E")+
  theme_classic()+
  theme(legend.position = "none",
    panel.background = element_rect(fill = "white", colour = "grey50"),
    axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))

part1

ggsave("Fig 7_part120240109.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 8,height = 8,units = "cm")

# part3
part2 <- ggplot(data = data_var,
                aes(x = Dim.2, y = reorder(Trait,Dim.2)))+
  geom_bar(stat = "identity",aes(fill = Dim.2))+
  xlab("PCA 2")+
  ylab(NULL)+
  scale_color_viridis(discrete = TRUE,option = "E")+
  theme_classic()+
  theme(legend.position = "none",
    panel.background = element_rect(fill = "white", colour = "grey50"),
    axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"))

part2

ggsave("Fig 7_part220240109.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 8,height = 8,units = "cm")

# part4
spe.pca$ind$coord
spe.pca$ind$contrib
spe.pca$ind

data_ind <- spe.pca$ind$contrib[,1:2]
data_ind <- data.frame(data_ind,species=df4$species)
str(data_ind)

library(agricolae)
test <- aov(Dim.1~species,data = data_ind)
summary(test)
one <- HSD.test(test,"species")
one
#整理数据
mar <- one$groups
mean1 <- one$means[,1]
sd1 <- one$means[,2]
Q75 <- one$means[,8]
species <- c("cmnxj","jhh","ynp","xpc")
da1 <- data.frame(species,mar,sd1,Q75)


#Dim.1
library(ggpubr)
library(ggsignif)

my_col <- c("#1663A9","#EE4431","#614099","#B49D30")
part3 <- ggplot(data_ind,aes(x=species,
                             y=Dim.1,
                             fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=da1,
            aes(x=species,
                y=Dim.1+sd1+Q75+2,
                label=groups),
            stat = "identity")+
  ylab("PCA 1")+
  scale_fill_manual(values =my_col)+
  #theme(legend.position = "top")
  #stat_signif(comparisons = my_compare,map_signif_level = TRUE)+
  #stat_compare_means(comparisons = my_compare,label = "p.signif",method = "t.test") +
  #scale_color_manual(values =c("#1663A9","#EE4431","#614099","#B49D30"))+
  scale_x_discrete(name="Species",
                   labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme_classic()+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black",face = "italic"))
   

part3

ggsave("Fig 7_part320240109.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 8,height = 8,units = "cm")

##找图例
ggplot(data_ind, aes(x=species,y=Dim.1)) +     
  geom_boxplot(aes(fill=species))+
  scale_fill_manual(values =my_col)
  
ggsave("Fig 7_test20240109_.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 20,height = 16,units = "cm")


#Dim.2
library(agricolae)
test2 <- aov(Dim.2~species,data = data_ind)
summary(test2)
one2 <- HSD.test(test2,"species")
one2
#整理数据
mar2 <- one2$groups
mean2 <- one2$means[,1]
sd2 <- one2$means[,2]
Q75_2 <- one2$means[,8]
species1 <- c("jhh","xpc","cmnxj","ynp")
da2 <- data.frame(species1,mar2,sd2,Q75_2) %>% 
  arrange(species1)


#Dim.2
library(ggpubr)
library(ggsignif)

part4 <- ggplot(data_ind,aes(x=species,
                             y=Dim.2,
                             fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=da2,
            aes(x=species,
                y=Dim.2+Q75_2+4.7,
                label=groups),
            stat = "identity")+
  #stat_signif(comparisons = my_compare,map_signif_level = TRUE)+
  #stat_compare_means(comparisons = my_compare,label = "p.signif",method = "t.test") +
  #scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  ylab("PCA 2")+
  scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme_classic()+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black",face = "italic"))
   

part4

ggsave("Fig 7_part420240109.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 8,height = 8,units = "cm")


# summary(PCA)
# attributes(PCA)
# plot(PCA)
plot(PCA$x[,1],PCA$x[,2])
df_p <- data.frame(PCA$x,species=df4$species)
head(df_p)

ggplot(df_p,aes(x=PC1,y=PC2,color=species))+ geom_point()


pairs.panels(PCA$x,
             gap=0,
             pch=21)

library(devtools)
#install_github("vqv/ggbiplot")
library(ggbiplot)
g <- ggbiplot(PCA,
              obs.scale = 1,
              var.scale = 1,
              groups = df2$species,
              ellipse = TRUE,
              ellipse.prob = 0.95,
              varname.size = 3) +
              #circle = TRUE,
              #ellipse.prob = 0.68) +
  scale_color_discrete(name = '') + 
  geom_point(aes(shape = df2$species,color=df2$elevation))+
  # geom_point(aes(colour=data_species$species,
  #                shape=data_species$species), size = 2) +
  #scale_color_brewer(name = "species",palette = "Set2") +
  #scale_color_manual(name = "Species",values = c("")) +
  #scale_color_gradient(low = "white", high = "red")
  #scale_shape_manual(name = "species",values = c(16:19)) + 
   
  theme(legend.direction = 'vertical',
        legend.position = 'right',
        legend.background = element_rect())

print(g)

ggsave("Fig 31.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 20,height = 20,units = "cm")

#####NEW


fviz_pca_ind(PCA,pointsize = df2$elevation)
fviz_pca_var(PCA)
PCA %>% summary()
PCA$x

fviz_contrib(PCA, choice = "var", axes = 1, top = 10)

fviz_contrib(PCA, choice = "var", axes = 2, top = 10)

# make pca
PCA <- prcomp(df3,center = TRUE, scale = TRUE)
summary(PCA)
attributes(PCA)
plot(PCA)


pairs.panels(PCA$x,
             gap=0,
             pch=21)

library(devtools)
#install_github("vqv/ggbiplot")
library(ggbiplot)
g <- ggbiplot(PCA,
              obs.scale = 1,
              var.scale = 1,
              groups = df2$species,
              ellipse = TRUE,
              ellipse.prob = 0.95,
              varname.size = 3) +
              #circle = TRUE,
              #ellipse.prob = 0.68) +
  scale_color_discrete(name = '') + 
  # geom_point(aes(colour=data_species$species,
  #                shape=data_species$species), size = 2) +
  #scale_color_brewer(name = "species",palette = "Set2") +
  #scale_color_manual(name = "Species",values = c("")) +
  #scale_color_gradient(low = "white", high = "red")
  #scale_shape_manual(name = "species",values = c(16:19)) + 
   
  theme(legend.direction = 'vertical',
        legend.position = 'right',
        legend.background = element_rect())

print(g)

ggsave("Fig 3.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 20,height = 20,units = "cm")
```


# Anova
```{r}
str(df0)
colnames(df0)
my_col <- c("#1663A9","#EE4431","#614099","#B49D30")

## RSR
RSRano <- aov(log10(rootshootration)~species,data = df0)
summary(RSRano)
RSR_mulcomp <- HSD.test(RSRano,"species")
RSR_mulcomp

  
RSR_da <- data.frame(species = c("jhh","ynp","xpc","cmnxj"),
                  RSR_mulcomp$groups) %>% 
  arrange(species)


RSRp <- ggplot(df0,
               aes(x=species,
                   y=log10(rootshootration),
                   fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=RSR_da,aes(x=species,
                            y=log10.rootshootration.+1.6,
                            label=groups), 
            stat = "identity",
            size = 4.5)+
  ylab("Root shoot ratio")+
  xlab(NULL)+
  scale_fill_manual(values =my_col)+
  # scale_x_discrete(
  #   name="Species",
  #   labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme_classic()+
  theme(legend.position = "right",
        axis.text.x = element_blank(),
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black")
        # axis.text.x = element_text(size = 10, colour = "black",face = "italic")
        )
   
RSRp


## RMR
RMRano <- aov(log10(RMR)~species,data = df0)
summary(RMRano)
RMR_mulcomp <- HSD.test(RMRano,"species")
RMR_mulcomp

RMR_da <- data.frame(species = c("jhh","ynp","xpc","cmnxj"),
                  RMR_mulcomp$groups) %>% 
  arrange(species)


RMRp <- ggplot(df0,aes(x=species,y=log10(RMR),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=RMR_da,
            aes(x=species,
                y=log10.RMR.+1.2,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Root mass ratio")+
  xlab(NULL)+
  # ylim(-3,1)+
  scale_fill_manual(values =my_col)+
  # scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+#
  theme_classic()+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        # axis.text.x = element_text(size = 10, colour = "black",face = "italic")
        )
   
RMRp


## SMR
SMRano <- aov(log10(SMR)~species,data = df0)
summary(SMRano)
SMR_mulcomp <- HSD.test(SMRano,"species")
SMR_mulcomp


SMR_da <- data.frame(species = c("ynp","xpc","jhh","cmnxj"),
                  SMR_mulcomp$groups) %>% 
  arrange(species)


SMRp <- ggplot(df0,
               aes(x=species,
                   y=log10(SMR),
                   fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=SMR_da,
            aes(x=species,
                y=log10.SMR.+0.7,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Stem mass ratio")+
  xlab(NULL)+
  theme_classic()+
  scale_fill_manual(values =my_col)+
  #scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black")
        #,axis.text.x = element_text(size = 20, colour = "black",face = "italic")
        )
   
SMRp



## LMR
LMRano <- aov(log10(LMR)~species,data = df0)
summary(LMRano)
LMR_mulcomp <- HSD.test(LMRano,"species")
LMR_mulcomp


LMR_da <- data.frame(species = c("cmnxj","xpc","jhh","ynp"),
                  LMR_mulcomp$groups) %>% 
  arrange(species)


LMRp <- ggplot(df0,aes(x=species,y=log10(LMR),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=LMR_da,
            aes(x=species,
                y=log10.LMR.+0.95,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Leaf mass ratio")+
  xlab(NULL)+
  scale_fill_manual(values =my_col)+
  #scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme_classic()+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black")
        #,axis.text.x = element_text(size = 20, colour = "black",face = "italic")
        )
   
LMRp

#fig 8
# plot_grid(LMRp,RMRp,SMRp,RSRp,
#           labels = "AUTO", 
#           label_size = 12, 
#           ncol = 2)
# 
# ggsave("Fig 8.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 28,height = 25,units = "cm")
# 
# ggsave("Fig 8.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 28,height = 25,units = "cm")


## SRL
SRLano <- aov(log10(SRL)~species,data = df0)
summary(SRLano)
SRL_mulcomp <- HSD.test(SRLano,"species")
SRL_mulcomp

SRL_da <- data.frame(species = c("cmnxj","xpc","ynp","jhh"),
                  SRL_mulcomp$groups) %>% 
  arrange(species)


SRLp <- ggplot(df0,aes(x=species,y=log10(SRL),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=SRL_da,
            aes(x=species,
                y=log10.SRL.+1.7,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Specific root length (mm/g)")+
  xlab(NULL)+
  scale_fill_manual(values =my_col)+
  theme_classic()+
  #scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        #axis.text.x = element_text(size = 13, colour = "black",face = "italic")
        )
   
SRLp



## SLA
SLAano <- aov(log10(SLA)~species,data = df0)
summary(SLAano)
SLA_mulcomp <- HSD.test(SLAano,"species")
SLA_mulcomp

SLA_da <- data.frame(species = c("cmnxj","xpc","ynp","jhh"),
                  SLA_mulcomp$groups) %>% 
  arrange(species)


SLAp <- ggplot(df0,aes(x=species,y=log10(SLA),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=SLA_da,
            aes(x=species,
                y=log10.SLA.+1,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Specific leaf area (cm2/g)")+
  xlab(NULL)+
  # ylim(4.9,7.7)+
  scale_fill_manual(values =my_col)+
  theme_classic()+
  #scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),#,vjust = 1.5
        axis.text.y = element_text(size = 10, colour = "black"),#,vjust = 0.5
        #axis.text.x = element_text(size = 13, colour = "black",face = "italic")
        )
   
SLAp

## SRA
SRAano <- aov(log10(SRA)~species,data = df0)
summary(SRAano)
SRA_mulcomp <- HSD.test(SRAano,"species")
SRA_mulcomp

SRA_da <- data.frame(species = c("cmnxj","xpc","ynp","jhh"),
                  SRA_mulcomp$groups) %>% 
  arrange(species)


SRAp <- ggplot(df0,aes(x=species,y=log10(SRA),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=SRA_da,
            aes(x=species,
                y=log10.SRA.+1.7,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Specific root area (mm2/g)")+
  xlab(NULL)+
  theme_classic()+
  scale_fill_manual(values =my_col)+
  #scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        #axis.text.x = element_text(size = 13, colour = "black",face = "italic")
        )
   
SRAp

## RTD
RTDano <- aov(log10(RTD)~species,data = df0)
summary(RTDano)
RTD_mulcomp <- HSD.test(RTDano,"species")
RTD_mulcomp

RTD_da <- data.frame(species = c("jhh","xpc","ynp","cmnxj"),
                  RTD_mulcomp$groups) %>% 
  arrange(species)


RTDp <- ggplot(df0,aes(x=species,y=log10(RTD),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=RTD_da,
            aes(x=species,
                y=log10.RTD.+3.1,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Root tissue density (g/mm3)")+
  xlab(NULL)+
  theme_classic()+
  scale_fill_manual(values =my_col)+
  #scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),#,vjust = -1
        #axis.text.x = element_text(size = 13, colour = "black",face = "italic")
        )

RTDp

#fig 9
# plot_grid(SRLp,SLAp,SRAp,RTDp,
#           labels = "AUTO", 
#           label_size = 12, 
#           ncol = 2)
# 
# ggsave("Fig 9.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 28,height = 25,units = "cm")
# 
# ggsave("Fig 9.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 28,height = 25,units = "cm")

plot_grid(SLAp,SRLp,SRAp,RTDp,LMRp,SMRp,RMRp,RSRp,
          labels = "AUTO", 
          align = "v",
          label_size = 14, 
          ncol = 3)+
  theme(plot.margin = margin(0.1,0.1,1,0.1,unit = "cm"))

ggsave("Fig 2_20240109_1.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 20,height = 18,units = "cm")

## Fine_root_length
FRLano <- aov(log10(Fine_root_length)~species,data = df0)
summary(FRLano)
FRL_mulcomp <- HSD.test(FRLano,"species")
FRL_mulcomp

FRL_da <- data.frame(species = c("cmnxj","jhh","xpc","ynp"),
                  FRL_mulcomp$groups) %>% 
  arrange(species)


FRLp <- ggplot(df0,aes(x=species,y=log10(Fine_root_length),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=FRL_da,
            aes(x=species,
                y=log10.Fine_root_length.+1,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Fine root length (mm)")+
  xlab(NULL)+
  scale_fill_manual(values =my_col)+
  #scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme_classic()+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        #axis.text.x = element_text(size = 13, colour = "black",face = "italic")
        )

FRLp


## Fine_root_area
FRAano <- aov(log10(Fine_root_area)~species,data = df0)
summary(FRAano)
FRA_mulcomp <- HSD.test(FRAano,"species")
FRA_mulcomp

FRA_da <- data.frame(species = c("jhh","cmnxj","xpc","ynp"),
                  FRA_mulcomp$groups) %>% 
  arrange(species)


FRAp <- ggplot(df0,aes(x=species,y=log10(Fine_root_area),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=FRA_da,
            aes(x=species,
                y=log10.Fine_root_area.+1,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Fine root area (mm2)")+
  xlab(NULL)+
  scale_fill_manual(values =my_col)+
  #scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme_classic()+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        #axis.text.x = element_text(size = 13, colour = "black",face = "italic")
        )

FRAp

## Fine_root_volume
FRVano <- aov(log10(Fine_root_volume)~species,data = df0)
summary(FRVano)
FRV_mulcomp <- HSD.test(FRVano,"species")
FRV_mulcomp

FRV_da <- data.frame(species = c("jhh","cmnxj","xpc","ynp"),
                  FRV_mulcomp$groups) %>% 
  arrange(species)


FRVp <- ggplot(df0,aes(x=species,y=log10(Fine_root_volume),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=FRV_da,
            aes(x=species,
                y=log10.Fine_root_volume.+2.7,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Fine root volume (mm3)")+
  # ylim(5.2,10.5)+
  xlab(NULL)+
  scale_fill_manual(values =my_col)+
  theme_classic()+
  #scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        #axis.text.x = element_text(size = 13, colour = "black",face = "italic")
        )

FRVp

#fig 10
# plot_grid(FRLp,FRAp,FRVp,
#           labels = "AUTO", 
#           label_size = 12, 
#           ncol = 3)
# 
# ggsave("Fig 10.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 40,height = 15,units = "cm")
# 
# ggsave("Fig 10.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 40,height = 13,units = "cm")


##mass anova
str(df0)
colnames(df0)
totalmass_dry
stem_dry
leaf_totalmass
root_dry
my_col <- c("#1663A9","#EE4431","#614099","#B49D30")

## TM
TMano <- aov(log(totalmass_dry)~species,data = df0)
summary(TMano)
TM_mulcomp <- HSD.test(TMano,"species")
TM_mulcomp

  
TM_da <- data.frame(species = c("jhh","ynp","xpc","cmnxj"),
                  TM_mulcomp$groups) %>% 
  arrange(species)


TMp <- ggplot(df0,aes(x=species,y=log(totalmass_dry),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=TM_da,aes(x=species,y=log.totalmass_dry.+2.6,label=groups), stat = "identity",size = 5.5)+
  ylab("Total dry mass (g)")+
  #xlab(NULL)+
  scale_fill_manual(values =my_col)+
  scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme(legend.position = "right",
        #axis.text.x = element_blank(),
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 17, color = "black"),
        axis.text.y = element_text(size = 13, colour = "black"),
        axis.text.x = element_text(size = 13, colour = "black",face = "italic")
        )
   
TMp


## RM
totalmass_dry
stem_dry
leaf_totalmass
root_dry
RMano <- aov(log10(root_dry)~species,data = df0)
summary(RMano)
RM_mulcomp <- HSD.test(RMano,"species")
RM_mulcomp

RM_da <- data.frame(species = c("jhh","ynp","xpc","cmnxj"),
                  RM_mulcomp$groups) %>% 
  arrange(species)


RMp <- ggplot(df0,aes(x=species,y=log10(root_dry),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=RM_da,
            aes(x=species,
                y=log10.root_dry.+1.2,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Root dry mass (g)")+
  xlab(NULL)+
  #ylim(-3,1)+
  scale_fill_manual(values =my_col)+
  theme_classic()+
  # scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        # axis.text.x = element_text(size = 14, colour = "black",face = "italic")
        )
   
RMp


## SMR  totalmass_dry stem_dry leaf_totalmass root_dry
SMano <- aov(log10(stem_dry)~species,data = df0)
summary(SMano)
SM_mulcomp <- HSD.test(SMano,"species")
SM_mulcomp

SM_da <- data.frame(species = c("jhh","ynp","xpc","cmnxj"),
                  SM_mulcomp$groups) %>% 
  arrange(species)

SMp <- ggplot(df0,aes(x=species,y=log10(stem_dry),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=SM_da,
            aes(x=species,
                y=log10.stem_dry.+1.3,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Stem dry mass (g)")+
  xlab(NULL)+
  scale_fill_manual(values =my_col)+
  # scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme_classic()+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        # axis.text.x = element_text(size = 14, colour = "black",face = "italic")
        )
   
SMp



## LMR  totalmass_dry stem_dry leaf_totalmass root_dry
LMano <- aov(log10(leaf_totalmass)~species,data = df0)
summary(LMano)
LM_mulcomp <- HSD.test(LMano,"species")
LM_mulcomp


LM_da <- data.frame(species = c("jhh","xpc","cmnxj","ynp"),
                  LM_mulcomp$groups) %>% 
  arrange(species)


LMp <- ggplot(df0,aes(x=species,y=log10(leaf_totalmass),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=LM_da,
            aes(x=species,
                y=log10.leaf_totalmass.+1,
                label=groups),
            stat = "identity",size = 4.5)+
  ylab("Leaf dry mass (g)")+
  xlab(NULL)+
  scale_fill_manual(values =my_col)+
  # scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme_classic()+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        # axis.text.x = element_text(size = 14, colour = "black",face = "italic")
        )
   
LMp

#fig S3
plot_grid(FRLp,FRAp,FRVp,
          LMp,SMp,RMp,
          align = "v",
          labels = "AUTO", 
          label_size = 14, 
          ncol = 3)+theme(plot.margin = margin(0.1,0.1,1,0.1,unit = "cm"))

ggsave("Fig S320240109.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 20,height = 12,units = "cm")

ggsave("Fig S3.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 45,height = 30,units = "cm")


```

# add
```{r}
str(df0)
#root_dry随海拔变化趋势
RMmd <- lm(log(root_dry)~elevation,data = df0)
summary(RMmd)
plot(RMmd)

RM <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log(root_dry), 
             group = species, 
             color = species)) +
  geom_point(size = 3, alpha = 1) +
  #scale_color_tron()+
  #scale_fill_tron()+
  #scale_color_brewer(palette = "Dark2") +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  xlab("Elevation (m)")+
  ylab("Root dry mass (g)")+
  ylim(-3.7,2.5)+
  #geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("jhh","xpc"))) +
  #stat_smooth(mapping = c(x = elevation, y = log(rootshootration)),data = df0,method = "lm")+
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size = 5) + 
  theme(legend.position = "none",
        #legend.direction = "horizontal",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        #axis.text.x = element_blank(),
        axis.title = element_text(size = 17, color = "black"),
        axis.text = element_text(size = 13, colour = "black")) 
  
  #theme(legend.position = "right", panel.background = element_rect(fill = "white", colour = "grey50"))

RM

ggplot(data = df0,aes(x = elevation, 
             y = log(stem_dry),group = species, 
             color = species)) +
  geom_smooth(method = "lm", formula = y~x, data = df0)+
  stat_poly_eq(use_label(c("adj.R2","P","eq")))


#totalmass_dry
TMmd <- lm(log(totalmass_dry)~elevation,data = df0)
summary(TMmd)
plot(TMmd)

TM <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log(totalmass_dry), 
             group = species, 
             color = species)) +
  geom_point(size = 3, alpha = 1) +
  #scale_color_tron()+
  #scale_fill_tron()+
  #scale_color_brewer(palette = "Dark2") +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  xlab("Elevation (m)")+
  ylab("Total dry mass (g)")+
  ylim(-2,3.5)+
  #geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("jhh","xpc"))) +
  #stat_smooth(mapping = c(x = elevation, y = log(rootshootration)),data = df0,method = "lm")+
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size = 5) + 
  theme(legend.position = "none",
        #legend.direction = "horizontal",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        #axis.text.x = element_blank(),
        axis.title = element_text(size = 17, color = "black"),
        axis.text = element_text(size = 13, colour = "black")) 
  
  #theme(legend.position = "right", panel.background = element_rect(fill = "white", colour = "grey50"))

TM


#leaf_totalmass
LMmd <- lm(log(leaf_totalmass)~elevation,data = df0)
summary(LMmd)
plot(LMmd)

LM <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log(leaf_totalmass), 
             group = species, 
             color = species)) +
  geom_point(size = 3, alpha = 1) +
  #scale_color_tron()+
  #scale_fill_tron()+
  #scale_color_brewer(palette = "Dark2") +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  xlab("Elevation (m)")+
  ylab("Leaf dry mass (g)")+
  ylim(-3,3)+
  #geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("jhh","xpc"))) +
  #stat_smooth(mapping = c(x = elevation, y = log(rootshootration)),data = df0,method = "lm")+
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size = 5) + 
  theme(legend.position = "none",
        #legend.direction = "horizontal",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        #axis.text.x = element_blank(),
        axis.title = element_text(size = 17, color = "black"),
        axis.text = element_text(size = 13, colour = "black")) 
  
  #theme(legend.position = "right", panel.background = element_rect(fill = "white", colour = "grey50"))

LM



#stem_dry
SMmd <- lm(log(stem_dry)~elevation,data = df0)
summary(SMmd)
plot(SMmd)

SM <- df0 %>% 
  ggplot(aes(x = elevation, 
             y = log(stem_dry), 
             group = species, 
             color = species)) +
  geom_point(size = 3, alpha = 1) +
  #scale_color_tron()+
  #scale_fill_tron()+
  #scale_color_brewer(palette = "Dark2") +
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"))+
  xlab("Elevation (m)")+
  ylab("Stem dry mass (g)")+
  ylim(-3,2.5)+
  #geom_smooth(method = "lm", formula = y~x, data = subset(df0, species ==c("jhh","xpc"))) +
  #stat_smooth(mapping = c(x = elevation, y = log(rootshootration)),data = df0,method = "lm")+
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P")),size = 5) + 
  theme(legend.position = "none",
        #legend.direction = "horizontal",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        #axis.text.x = element_blank(),
        axis.title = element_text(size = 17, color = "black"),
        axis.text = element_text(size = 13, colour = "black")) 
  
  #theme(legend.position = "right", panel.background = element_rect(fill = "white", colour = "grey50"))

SM

#Fig 14
plot_grid(LM,RM,TM,SM,
          labels = "AUTO", 
          label_size = 12, 
          ncol = 2)

ggsave("Fig 14.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 28,height = 25,units = "cm")


####-----#####MASS 
#####RMR vs LMR
str(df0)
stem_dry
leaf_totalmass
root_dry
df0 %>% 
  ggplot(aes(x = log(leaf_totalmass), 
             y = log(root_dry), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"))


fit24 <- sma(root_dry~leaf_totalmass*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit24)
plot(fit24)

data24 <- data.frame(fit24[["data"]])
pval24 <- fit24[["pval"]] 

p24 <- ggplot(data24,mapping = aes(x=leaf_totalmass,y=root_dry, colour=species)) +
  xlab("Leaf dry mass (g)") +
  ylab("Root dry mass (g)") + 
  #xlim(2.15,3.05) +
  #ylim(-1.3,-0.02) +
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  geom_point(size = 3, alpha = 1) +
  #geom_point(aes(shape = species))+
  #stat_poly_line(formula = y ~ x,method = "lm") +
  stat_poly_line(method = "lm",formula = y ~ x) +
  stat_poly_eq(use_label(c("adj.R2","P"))) + 
  annotate("text", label = c("Slope\njhh-ynp:**\nxpc-ynp:**"), x = -0.8, y = -0.3, size = 4)+
  #geom_abline(intercept = 0, slope = 1)+
  #abline(0, 0.5, col = "black")+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 17, color = "black"),
        legend.text = element_text(size = 12,face = "italic"),
        axis.text.y = element_text(size = 13, colour = "black"),
        axis.text.x = element_text(size = 13, colour = "black"))
p24


####RMR vs SMR
stem_dry
leaf_totalmass
root_dry
df0 %>% 
  ggplot(aes(x = log(stem_dry), 
             y = log(root_dry), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "top",panel.background = element_rect(fill = "white", colour = "grey50"))

fit25 <- sma(root_dry~stem_dry*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit25)
plot(fit25)

data25 <- data.frame(fit25[["data"]])
pval25 <- fit25[["pval"]] 

p25 <- ggplot(data25,mapping = aes(x=stem_dry,y=root_dry, colour=species)) +
  xlab("Stem dry mass (g)") +
  ylab("Root dry mass (g)") + 
  #xlim(2.15,3.05) +
  #ylim(-1.3,0.15) +
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  geom_point(size = 3, alpha = 1) +
  #geom_point(aes(shape = species))+
  stat_poly_line(method = "lm",formula = y ~ x) +
  stat_poly_eq(use_label(c("adj.R2","P"))) + 
  annotate("text", label = c("Slope\nxpc-ynp:**"), x = -1, y = -0.3, size = 4)+
  #geom_abline(intercept = 0, slope = 1)+
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 17, color = "black"),
        legend.text = element_text(size = 12,face = "italic"),
        axis.text.y = element_text(size = 13, colour = "black"),
        axis.text.x = element_text(size = 13, colour = "black"))
p25


####LMR vs SMR
stem_dry
leaf_totalmass
root_dry
df0 %>% 
  ggplot(aes(x = log(stem_dry), 
             y = log(leaf_totalmass), 
             group = species, 
             color = species)) +
  #xlab("Elevation")+
  geom_point(size = 2, alpha = 1) +
  geom_smooth(method = "lm", formula = y~x) +
  #stat_poly_line(formula = y~x,method = "lm") +
  stat_poly_eq(use_label(c("R2","P"))) + 
  theme(legend.position = "none",panel.background = element_rect(fill = "white", colour = "grey50"))

fit26 <- sma(leaf_totalmass~stem_dry*species,data = df2, log = "xy",robust=T,multcomp = TRUE,multcompmethod = "adjusted")
summary(fit26)
plot(fit26)

data26 <- data.frame(fit26[["data"]])
pval26 <- fit26[["pval"]] 

p26 <- ggplot(data26,mapping = aes(x=stem_dry,y=leaf_totalmass, colour=species)) +
  xlab("Stem dry mass (g)") +
  ylab("Leaf dry mass (g)") + 
  #xlim(2.15,3.05) +
  ylim(-1.6,0.65) +
  #scale_color_tron()+
  #scale_fill_tron()+
  scale_color_manual(values = c("#1663A9","#EE4431","#614099","#B49D30"),name = "Species",breaks = c("cmnxj","jhh","xpc","ynp"),labels = c("Galinsoga quadriradiata","Solidago canadensis","Erigeron canadensis","Erigeron annuus"))+
  geom_point(size = 3, alpha = 1) +
  #geom_point(aes(shape = species))+
  stat_poly_line(formula = y ~ x,method = "lm") +
  stat_poly_eq(use_label(c("adj.R2","P"))) + 
  annotate("text", label = c("Slope:ns"), x = -1, y = 0, size = 4)+
  annotate(geom = "segment",x=-1,y=-1.5,xend=0.5,yend = 0.5)+
  #geom_abline(intercept = 0, slope = 1)+
  theme(legend.position = c(0.7,0.15),panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 17, color = "black"),
        legend.text = element_text(size = 12,face = "italic"),
        axis.text.y = element_text(size = 13, colour = "black"),
        axis.text.x = element_text(size = 13, colour = "black"))
p26

#Fig 15
plot_grid(p24,p25,p26,
          labels = "AUTO", 
          ncol = 3,
          label_size = 12)

ggsave("Fig 15.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 50,height = 15,units = "cm")

ggsave("Fig 15.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 40,height = 15,units = "cm")


##mass anova
str(df0)
colnames(df0)
totalmass_dry
stem_dry
leaf_totalmass
root_dry
my_col <- c("#1663A9","#EE4431","#614099","#B49D30")

## TM
TMano <- aov(log(totalmass_dry)~species,data = df0)
summary(TMano)
TM_mulcomp <- HSD.test(TMano,"species")
TM_mulcomp

  
TM_da <- data.frame(species = c("jhh","ynp","xpc","cmnxj"),
                  TM_mulcomp$groups) %>% 
  arrange(species)


TMp <- ggplot(df0,aes(x=species,y=log(totalmass_dry),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=TM_da,aes(x=species,y=log.totalmass_dry.+2.6,label=groups), stat = "identity",size = 5.5)+
  ylab("Total dry mass (g)")+
  #xlab(NULL)+
  scale_fill_manual(values =my_col)+
  scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme(legend.position = "right",
        #axis.text.x = element_blank(),
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 17, color = "black"),
        axis.text.y = element_text(size = 13, colour = "black"),
        axis.text.x = element_text(size = 13, colour = "black",face = "italic")
        )
   
TMp


## RM
totalmass_dry
stem_dry
leaf_totalmass
root_dry
RMano <- aov(log(root_dry)~species,data = df0)
summary(RMano)
RM_mulcomp <- HSD.test(RMano,"species")
RM_mulcomp

RM_da <- data.frame(species = c("jhh","ynp","xpc","cmnxj"),
                  RM_mulcomp$groups) %>% 
  arrange(species)


RMp <- ggplot(df0,aes(x=species,y=log(root_dry),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=RM_da,
            aes(x=species,
                y=log.root_dry.+2.2,
                label=groups),
            stat = "identity",size = 5.5)+
  ylab("Root dry mass (g)")+
  xlab(NULL)+
  #ylim(-3,1)+
  scale_fill_manual(values =my_col)+
  #scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 17, color = "black"),
        axis.text.y = element_text(size = 13, colour = "black"),
        #axis.text.x = element_text(size = 12, colour = "black",face = "italic")
        )
   
RMp


## SMR  totalmass_dry stem_dry leaf_totalmass root_dry
SMano <- aov(log(stem_dry)~species,data = df0)
summary(SMano)
SM_mulcomp <- HSD.test(SMano,"species")
SM_mulcomp

SM_da <- data.frame(species = c("jhh","ynp","xpc","cmnxj"),
                  SM_mulcomp$groups) %>% 
  arrange(species)

SMp <- ggplot(df0,aes(x=species,y=log(stem_dry),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=SM_da,
            aes(x=species,
                y=log.stem_dry.+2.1,
                label=groups),
            stat = "identity",size = 5.5)+
  ylab("Stem dry mass (g)")+
  scale_fill_manual(values =my_col)+
  scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.title = element_text(size = 17, color = "black"),
        axis.text.y = element_text(size = 13, colour = "black"),
        axis.text.x = element_text(size = 13, colour = "black",face = "italic"))
   
SMp



## LMR  totalmass_dry stem_dry leaf_totalmass root_dry
LMano <- aov(log(leaf_totalmass)~species,data = df0)
summary(LMano)
LM_mulcomp <- HSD.test(LMano,"species")
LM_mulcomp


LM_da <- data.frame(species = c("jhh","xpc","cmnxj","ynp"),
                  LM_mulcomp$groups) %>% 
  arrange(species)


LMp <- ggplot(df0,aes(x=species,y=log(leaf_totalmass),fill=species))+
  geom_boxplot(fill=my_col)+
  geom_text(data=LM_da,
            aes(x=species,
                y=log.leaf_totalmass.+2.3,
                label=groups),
            stat = "identity",size = 5.5)+
  ylab("Leaf dry mass (g)")+
  xlab(NULL)+
  scale_fill_manual(values =my_col)+
  #scale_x_discrete(name="Species",labels = c("Ga. qu.","So. ca.","Er. ca.","Er. an."))+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "grey50"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 17, color = "black"),
        axis.text.y = element_text(size = 13, colour = "black")
        #axis.text.x = element_text(size = 13, colour = "black",face = "italic")
        )
   
LMp

#fig 16
plot_grid(LMp,RMp,SMp,TMp,
          labels = "AUTO", 
          label_size = 12, 
          ncol = 2)

ggsave("Fig 16.pdf", plot = last_plot(), device="pdf", dpi = 300, limitsize = F, width = 28,height = 25,units = "cm")

ggsave("Fig 16.tiff", plot = last_plot(), device="tiff", dpi = 300, limitsize = F, width = 28,height = 25,units = "cm")

```

